apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageclasscapabilities.storage.kubesphere.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: storage.kubesphere.io
  version: v1alpha1
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storageclasscapabilities
    # singular name to be used as an alias on the CLI and for display
    singular: storageclasscapability
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StorageClassCapability
    shortNames:
      - sccap
  preserveUnknownFields: false
  additionalPrinterColumns:
    - name: Provisioner
      type: string
      JSONPath: .spec.provisioner
    - name: Volume
      type: boolean
      JSONPath: .spec.features.volume.create
    - name: Snapshot
      type: boolean
      JSONPath: .spec.features.snapshot.create
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Cluster
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            provisioner:
              type: string
            features:
              type: object
              properties:
                topology:
                  description: topology determines whether a provisioner support topology by looking up GetPluginCapabilities.PluginCapability
                  type: boolean
                volume:
                  type: object
                  properties:
                    create:
                      type: boolean
                    attach:
                      type: boolean
                    list:
                      type: boolean
                    clone:
                      description: Determined by storage provisioner capability
                      type: boolean
                    readOnlyAttach:
                      type: boolean
                    statics:
                      type: boolean
                    expand:
                      description: Determined by allowVolumeExpansion in storage class and storage provisioner capability
                      type: boolean
                snapshot:
                  type: object
                  properties:
                    create:
                      type: boolean
                    list:
                      type: boolean
                accessMode:
                  type: array
                  items:
                    type: string
                    enum: ["ReadWriteOnce", "ReadWriteMany", "ReadOnlyMany"]