apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: provisionercapablities.storage.kubesphere.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: storage.kubesphere.io
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: provisionercapablities
    # singular name to be used as an alias on the CLI and for display
    singular: provisionercapablity
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ProvisionerCapability
    # shortNames allow shorter string to match your resource on the CLI
    listKind: ProvisionerCapabilityList
    shortNames:
      - pcap
  preserveUnknownFields: false
  scope: Cluster
  subresources: {}
  additionalPrinterColumns:
    - name: Provisioner
      type: string
      description: The provisioner name should be the same as name
      JSONPath: .spec.pluginInfo.name
    - name: Version
      type: string
      JSONPath: .spec.pluginInfo.version
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      required:
        - spec
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object.'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents.'
          type: string
        spec:
          required:
            - pluginInfo
            - features
          type: object
          description: 'spec defines the desired characteristics of obejct'
          properties:
            pluginInfo:
              type: object
              description: 'Plugininfo represents plugin metadata'
              properties:
                name:
                  description: 'provisioner name'
                  type: string
                version:
                  description: 'plugin version'
                  type: string
            features:
              type: object
              description: 'Features represents plugin capability'
              properties:
                topology:
                  description: 'topology determines whether a provisioner support topology by looking up GetPluginCapabilities.PluginCapability'
                  type: boolean
                volume:
                  type: object
                  description: 'Volume represents whether plugin supports volume features'
                  properties:
                    create:
                      type: boolean
                    attach:
                      type: boolean
                    list:
                      type: boolean
                    clone:
                      type: boolean
                    readOnlyAttach:
                      type: boolean
                    statics:
                      type: boolean
                    expand:
                      type: boolean
                snapshot:
                  type: object
                  description: 'Snapshot represents whether plugin supports snapshot features'
                  properties:
                    create:
                      type: boolean
                    list:
                      type: boolean
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true