apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: storage-capability
    owner: yunify
    role: controller
    ver: v0.1.0
  name: storage-capability-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: storage-capability
    owner: yunify
    role: controller
    ver: v0.1.0
  name: storage-capability-controller
rules:
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "snapshot.storage.k8s.io"
    resources:
      - volumesnapshotclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.kubesphere.io"
    resources:
      - provisionercapabilities
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.kubesphere.io"
    resources:
      - storageclasscapabilities
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storage-capability
    owner: yunify
    role: controller
    ver: v0.1.0
  name: storage-capability-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-capability-controller
subjects:
  - kind: ServiceAccount
    name: storage-capability-controller
    namespace: kube-system
