apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: storage-capability
    owner: yunify
    role: sidecar
    ver: v0.1.0
  name: storage-capability-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-capability-sidecar
subjects:
  - kind: ServiceAccount
    name: storage-capability-sidecar
    namespace: kube-system