apiVersion: storage.kubesphere.io/v1alpha1
kind: StorageClassCapability
metadata:
  name: example-sc
spec:
  provisioner: "csi.example.sc"
  features:
    topology: true
    volume:
      create: true
      attach: true
      clone: true
      list: false
      readOnlyAttach: true
      statics: true
      expand: true
    snapshot:
      create: true
      list: false
    accessMode: ["ReadWriteOnce", "ReadWriteMany"]