apiVersion: storage.kubesphere.io/v1alpha1
kind: ProvisionerCapability
metadata:
  name: csi.example.io
spec:
  pluginInfo:
    name: "csi.example.io"
    version: "v1.0.0"
  features:
    topology: true
    volume:
      create: true
      attach: true
      list: false
      clone: true
      readOnlyAttach: false
      statics: true
      expand: true
    snapshot:
      create: true
      list: false